spring:
  application:
    name: bookstore-api
  
  datasource:
    url: jdbc:h2:mem:bookstoredb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  
  sql:
    init:
      mode: NEVER

server:
  port: 3001

logging:
  level:
    com.example.bookstore: DEBUG
    org.springframework.web: DEBUG 